@startuml ObjectDiagram.Linked_HCS_and_PR
'skinparam monochrome true
object "HealthcareService" as hs1 #LightYellow
object "PractitionerRole" as pr1 #LightYellow
object "Organization" as o1 #LightPink
object "Location" as l1 #LightYellow
object "Endpoint 1" as e1 #LightYellow
object "Endpoint 2" as e2
object "Endpoint 3" as e3
object "Practitioner" as p1 #LightPink

hs1 o-- o1
hs1 o-- l1
hs1 o-- e1
hs1 o-- e2

pr1 o-- p1
pr1 o-- l1 #IndianRed
pr1 o-- e3
pr1 o-- e1 #IndianRed
pr1 o-l- hs1 #IndianRed

@enduml