= Fachkonzept Anwendungskennzeichen
gematik, Systems Engineering
:source-highlighter: rouge
:title-page:
:imagesdir: /images/
ifdef::env-github[]
:toc: preamble
endif::[]
ifndef::env-github[]
:toc: left
endif::[]
:toclevels: 3
:toc-title: Inhaltsverzeichnis
//:sectnums:

image::gematik_logo.svg[gematik,float="right"]

== Analyse

=== Randbedingungen

- PS muss angepasst werden, damit das Anwendungskennzeichen ausgewertet werden kann.
- FHIR-Dir unterstützt bereits ein Anwendungskennzeichen (Endpoint.payloadType)
- KIM Adressen sind noch nicht im FHIR-Directory
- Wenn KIM-Adressen im FHIR-Directory eingetragen werden, dann muss bei Synchronisierung mit dem LDAP-Directory beachtet werden, dass Kassen nur eine KIM-Adresse haben dürfen (für die eAU), solange in der DomainID das Institutionskennzeichen steht.

=== Zu beachten

- Es wäre gut, wenn der Eigentümer im Self-Service-Portal nur eigene KIM-Adressen verwenden kann. Offen: wie kann das durchgesetzt werden?

=== Umsetzung im FHIR-Directory

- Anwendungskennzeichen über Endpoint Ressourcen, wie bei TIM
- PS muss FHIR-Directory verwenden um nach Einträgen zu suchen und erhält gleich den kompletten FHIR-Directory Komfort.
- Pflege soll durch PS erfolgen (entweder per OIDC Auth und Direktzugriff auf den FHIR-Proxy oder alternativ Konfig-Mail an den KIM-Anbieter und Pflege über REST-Schnittstelle), weil nur das PS weiß, welche KIM Anwendungen unterstützt werden. Auch im Self-Service-Portal soll der Nutzer zuordnen können, welche KIM-Adresse für welche KIM-Anwendung genutzt wird
- Mehrere Arbeitsplätze des PS müssen unterschieden werden können. Vorschlag: im Endpoint.name wird kodiert <PS-name;PS-Version;PS-NutzerID?>
- Verknüpfung Practitioner zu Organisation im Self-Service-Portal (SSP) mit Bestätigungsabfrage (Beispiel Arzt verknüpft sich mit Arztpraxis; Arztpraxis muss bestätigen, dass die Verknüpfung gewünscht ist). Bestätigung kann über das SSP erfolgen oder per TIM-Bot, wenn das SSP auch eine TIM-Adresse bekommt
- Die Verlinkung von PractitionerRole mit HealthcareService und HealthcareService.endpoint kann gleichzeitig erfolgen.

image::diagrams/ObjectDiagram.Linked_HCS_and_PR.svg[Verlinkung von PractitionerRole mit HealthcareService und HealthcareService.endpoint]

=== Umsetzung im LDAP-Directory

- vorerst nicht. Begründung: Die Umsetzung im FHIR-Directory muss sowieso erfolgen und ist einfacher, weil die benötigten FHIR-Ressourcen schon existieren. PS können schon jetzt auf FHIR umstellen.
